baseURL = "https://andreinc.net/"
canonifyURLs = false
relativeURLs = true
languageCode = 'en-us'
title = 'Personal Site of Andrei N. Ciobanu'

[outputFormats]
  [outputFormats.RSS]
    baseName = "feed"
  [outputFormats.programmingrss]
    mediaType = "application/rss+xml"
    baseName = "programming"
    rel = "alternate"
    isHTML = false
    isPlainText = false
    ugly = true
  [outputFormats.mathrss]
    mediaType = "application/rss+xml"
    baseName = "math"
    rel = "alternate"
    isHTML = false
    isPlainText = false
    ugly = true
  [outputFormats.thoughtsrss]
    mediaType = "application/rss+xml"
    baseName = "thoughts"
    rel = "alternate"
    isHTML = false
    isPlainText = false
    ugly = true
  [outputFormats.olympiadrss]
    mediaType = "application/rss+xml"
    baseName = "olympiad"
    rel = "alternate"
    isHTML = false
    isPlainText = false
    ugly = true
  [outputFormats.linksrss]
    mediaType = "application/rss+xml"
    baseName = "links"
    rel = "alternate"
    isHTML = false
    isPlainText = false
    ugly = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
     style = 'modus-operandi'

[markup.goldmark.extensions.passthrough]
enable = true

[markup.goldmark.extensions.passthrough.delimiters]
  block = [['\\[', '\\]'], ['$$', '$$']]
  inline = [['\\(', '\\)']]

[markup.tableOfContents]
  startLevel = 1
  endLevel = 4
  ordered = false

[params]
  description = "A minimalist developer blog."
  author = "nomemory"
  favicon = "/favicon.svg"
  faviconPNG = "/favicon.png"
  hide_footer = true
  showQuote = true
  mainSections = ["/posts"]
  enablePostNavigator = true

[permalinks]
  posts = '/:year/:month/:day/:slug/'
  
[[menu.main]]
    identifier = "home"
    name = "home"
    url = "/"
    weight = 10
[[menu.main]]
    identifier = "about"
    name = "about"
    url = "/about/"
    weight = 11
[[menu.main]]
    identifier = "thoughts"
    name = "thoughts"
    url = "/categories/thoughts/"
    weight = 12
[[menu.main]]
    identifier = "math"
    name = "math"
    url = "/categories/math/"
    weight = 13
[[menu.main]]
    identifier = "programming"
    name = "programming"
    url = "/categories/programming/"
    weight = 14
[[menu.main]]
    identifier = "visuals"
    name = "visuals"
    url = "/visuals/"
    weight = 15
[[menu.main]]
    identifier = "jukebox"
    name = "jukebox"
    url = "/jukebox/"
    weight = 22
[[menu.main]]
    identifier = "lists"
    name = "lists"
    url = "/lists/"
    weight = 28
[[menu.main]]
    identifier = "links"
    name = "links"
    url = "/links/"
    weight = 30
[[menu.main]]
    identifier = "blogroll"
    name = "blogroll"
    url = "/blogroll/"
    weight = 40
[[menu.main]]
    identifier = "feeds"
    name = "feeds"
    url = "/feeds"
    weight = 100

[taxonomies]
  tag = "tags"
  category = "categories"
